version: "3"
services:

  app:
    container_name: movies
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "5005:80"

  postgres:
    container_name: movies-db
    image: postgres:9.6
    env_file: config/dev.env

    ports:
      - "5432:5432"
